import { ApiSequence } from '../types';

export const validFlows = [
  '1',
  '2',
  '012',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '020',
  '01C',
  '008',
  '003',
  '00F',
  '011',
  '017',
  '00D',
  '00E',
  '016',
  '01F'
];

export const flowSequences: Record<string, ApiSequence[]> = {
  '1': ['search', 'on_search', 'inc_search', 'inc_onsearch'],
  '2': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
  ],
  '3': [
    'search',
    'on_search',
    'select_out_of_stock',
    'on_select_out_of_stock',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
  ],
  '4': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'cancel',
    'on_cancel',
  ],
  '5': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_update_part_cancel',
    'update_settlement_part_cancel',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_cancel',
    'on_status_rto_delivered',
  ],
  '6': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
    'update_liquidated',
    'on_update_interim_liquidated',
    'on_update_liquidated',
    'update_settlement_liquidated',
  ],
  '7': ['search', 'on_search', 'catalog_rejection'],
  '8': ['search', 'on_search'],
  '9': ['inc_search', 'inc_onsearch', 'catalog_rejection'],
  '020': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
  ],
  '01C': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
  ],
  '008': ['search', 'on_search', 'select', 'on_select', 'init', 'on_init'],
  '003': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
  ],
  '00F': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'update_address',
    'on_update_address',
  ],
  '011': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'update_instructions',
    'on_update_instructions',
  ],
  '017': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
    'on_update',
    'on_cancel',
  ],
  '00D': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
    'cancel',
    'on_cancel',
  ],
  '00E': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'update',
  ],
  '012': [
    'search',
    'on_search',
    'select',
    'on_select',
    'init',
    'on_init',
    'confirm',
    'on_confirm',
    'on_status_pending',
    'on_status_packed',
    'on_status_picked',
    'on_status_out_for_delivery',
    'on_status_delivered',
  ],
  '016': ['search', 'on_search', 'select', 'on_select', 'init', 'on_init', 'confirm', 'on_confirm'],
  '01F': ['search', 'on_search', 'select', 'on_select', 'init', 'on_init', 'confirm', 'on_confirm'],
};

//   '1': [
//    SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.INC_SEARCH,
//     ApiSequence.INC_ONSEARCH,
//   ],
//   '2': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//   ],
//   '3': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT_OUT_OF_STOCK,
//     ApiSequence.ON_SELECT_OUT_OF_STOCK,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//   ],
//   '4': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.CANCEL,
//     ApiSequence.ON_CANCEL,
//   ],
//   '5': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_UPDATE_PART_CANCEL,
//     ApiSequence.UPDATE_SETTLEMENT_PART_CANCEL,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_CANCEL,
//     ApiSequence.ON_STATUS_RTO_DELIVERED
//   ],
//   '6': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//     ApiSequence.UPDATE_LIQUIDATED,
//     ApiSequence.ON_UPDATE_INTERIM_LIQUIDATED,
//     ApiSequence.ON_UPDATE_LIQUIDATED,
//     ApiSequence.UPDATE_SETTLEMENT_LIQUIDATED,
//   ],
//   '7': [ApiSequence.SEARCH, ApiSequence.ON_SEARCH, ApiSequence.CATALOG_REJECTION],
//   '8': [ApiSequence.SEARCH, ApiSequence.ON_SEARCH],
//   '9': [ApiSequence.INC_SEARCH, ApiSequence.INC_ONSEARCH, ApiSequence.CATALOG_REJECTION],
//   '020': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//   ],
//   '01C': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//   ],
//   '008': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//   ],
//   '003': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//   ],
//   '00F': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.UPDATE_ADDRESS,
//     ApiSequence.ON_UPDATE_ADDRESS,
//   ],
//   '011': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.UPDATE_INSTRUCTIONS,
//     ApiSequence.ON_UPDATE_INSTRUCTIONS,
//   ],
//   '017': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//     ApiSequence.ON_UPDATE,
//     ApiSequence.ON_CANCEL,
//   ],
//   '00D': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//     ApiSequence.CANCEL,
//     ApiSequence.ON_CANCEL,
//   ],
//   '00E': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.UPDATE,
//   ],
//   '012': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//     ApiSequence.ON_STATUS_PENDING,
//     ApiSequence.ON_STATUS_PACKED,
//     ApiSequence.ON_STATUS_PICKED,
//     ApiSequence.ON_STATUS_OUT_FOR_DELIVERY,
//     ApiSequence.ON_STATUS_DELIVERED,
//   ],
//   '016': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//   ],
//   '01F': [
//     ApiSequence.SEARCH,
//     ApiSequence.ON_SEARCH,
//     ApiSequence.SELECT,
//     ApiSequence.ON_SELECT,
//     ApiSequence.INIT,
//     ApiSequence.ON_INIT,
//     ApiSequence.CONFIRM,
//     ApiSequence.ON_CONFIRM,
//   ]
// };


// export const flowSequences: Record<string, ApiSequence[]> = {
//   '1': ['SEARCH', 'ON_SEARCH', 'INC_SEARCH', 'INC_ONSEARCH'],
//   '2': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//   ],
//   '3': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT_OUT_OF_STOCK',
//     'ON_SELECT_OUT_OF_STOCK',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//   ],
//   '4': ['SEARCH', 'ON_SEARCH', 'SELECT', 'ON_SELECT', 'INIT', 'ON_INIT', 'CONFIRM', 'ON_CONFIRM', 'CANCEL', 'ON_CANCEL'],
//   '5': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_UPDATE_PART_CANCEL',
//     'UPDATE_SETTLEMENT_PART_CANCEL',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_CANCEL',
//     'ON_STATUS_RTO_DELIVERED',
//   ],
//   '6': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//     'UPDATE_LIQUIDATED',
//     'ON_UPDATE_INTERIM_LIQUIDATED',
//     'ON_UPDATE_LIQUIDATED',
//     'UPDATE_SETTLEMENT_LIQUIDATED',
//   ],
//   '7': ['SEARCH', 'ON_SEARCH', 'CATALOG_REJECTION'],
//   '8': ['SEARCH', 'ON_SEARCH'],
//   '9': ['INC_SEARCH', 'INC_ONSEARCH', 'CATALOG_REJECTION'],
//   '020': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//   ],
//   '01C': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//   ],
//   '008': ['SEARCH', 'ON_SEARCH', 'SELECT', 'ON_SELECT', 'INIT', 'ON_INIT'],
//   '003': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//   ],
//   '00F': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'UPDATE_ADDRESS',
//     'ON_UPDATE_ADDRESS',
//   ],
//   '011': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'UPDATE_INSTRUCTIONS',
//     'ON_UPDATE_INSTRUCTIONS',
//   ],
//   '017': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//     'ON_UPDATE',
//     'ON_CANCEL',
//   ],
//   '00D': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//     'CANCEL',
//     'ON_CANCEL',
//   ],
//   '00E': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'UPDATE',
//   ],
//   '012': [
//     'SEARCH',
//     'ON_SEARCH',
//     'SELECT',
//     'ON_SELECT',
//     'INIT',
//     'ON_INIT',
//     'CONFIRM',
//     'ON_CONFIRM',
//     'ON_STATUS_PENDING',
//     'ON_STATUS_PACKED',
//     'ON_STATUS_PICKED',
//     'ON_STATUS_OUT_FOR_DELIVERY',
//     'ON_STATUS_DELIVERED',
//   ],
//   '016': ['SEARCH', 'ON_SEARCH', 'SELECT', 'ON_SELECT', 'INIT', 'ON_INIT', 'CONFIRM', 'ON_CONFIRM'],
//   '01F': ['SEARCH', 'ON_SEARCH', 'SELECT', 'ON_SELECT', 'INIT', 'ON_INIT', 'CONFIRM', 'ON_CONFIRM'],
// };